repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v0.8.0
    hooks:
      - id: go-test-mod
      - id: go-imports
        args:
          - -w
          - -local
          - github.com/storewise
      - id: golangci-lint-mod
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^\.bumpversion\.cfg$
      - id: trailing-whitespace
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.1
    hooks:
      - id: checkmake
  - repo: local
    hooks:
      - id: circleci_config_validate
        name: CircleCI config validate
        entry: circleci config validate
        language: python_venv
        files: ^\.circleci/config\.yml$