version: 2.1
orbs:
  go: circleci/go@1.5.0
jobs:
  build:
    executor:
      name: go/default
      tag: "1.15"
    environment:
      GOPRIVATE: github.com/storewise
    steps:
      - checkout
      - go/mod-download-cached
      - go/test
workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
