version: 2.1
orbs:
  go: circleci/go@1.6.0
jobs:
  build:
    executor:
      name: go/default
      tag: "1.16"
    environment:
      GOPRIVATE: github.com/storewise
    steps:
      - checkout
      - go/mod-download-cached
      - go/test:
          covermode: atomic
          race: true
          verbose: true
workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
